defaults:
  - override hydra/job_logging: custom
  - _self_

base_dataset:
  id: alexandrainst/multi-wiki-qa:da
  split: train
  context_key: context
  question_key: question
  answer_key: answers
  squad_format: true

model: gpt-4.1-mini
temperature: 1.0

beta_distribution:
  mean: 0.2
  std: 0.15

hub_organisation: alexandrainst
private: true

testing: false

save_dataset_to_file: false

training:
  output_dir: models
  batch_size: 1
  epochs: 5
  learning_rate: 1e-5
  weight_decay: 0.01
  language: da
  push_to_hub: True

models:
  target_model_name: ettin-encoder-17m-multi-wiki-qa-da
  pretrained_model_name: jhu-clsp/ettin-encoder-17m
  model_to_evaluate: Qwen/Qwen3-0.6B
