defaults:
  - override hydra/job_logging: custom
  - _self_

base_dataset:
  id: multi-wiki-qa
  organisation: alexandrainst
  split: train
  context_key: context
  question_key: question
  answer_key: answers
  squad_format: true

temperature: 1.0

beta_distribution:
  mean: 0.2
  std: 0.15

hub_organisation: alexandrainst
private: true

testing: false

save_dataset_to_file: false

training:
  output_dir: models
  batch_size: 1
  epochs: 5
  learning_rate: 1e-5
  weight_decay: 0.01
  push_to_hub: True

models:
  hallu_detect_model: ettin-encoder-17m
  pretrained_model: jhu-clsp/ettin-encoder-17m
  eval_model: Qwen/Qwen3-0.6B
  hallu_gen_model: gpt-4.1-mini

language: da
